DB_NAME = "snake"
DB_USER = "zhaslyk"
DB_PASSWORD = "asd123"
DB_HOST = "localhost"
DB_PORT = "5432"

WIDTH = 800
HEIGHT = 700
CELL_SIZE = 20

GAME_TOP = 80
GRID_WIDTH = WIDTH // CELL_SIZE
GRID_HEIGHT = (HEIGHT - GAME_TOP) // CELL_SIZE